### ISSUE TITLE
Modal causes "Can't perform a React state update on an unmounted component" warnings when using Testing Library

### ISSUE THREAD

**Issue by DanielGibbsNZ** [mantinedev/mantine#1008]
### What package has an issue

@mantine/core

### Problem

When writing Testing Library tests for an app using the `Modal` component, I get `Can't perform a React state update on an unmounted component` warnings when I have multiple tests in the file.

This can be demonstrated with the following basic app:

**App.tsx**

```
import React from 'react';
import { Button, Modal, Title } from '@mantine/core';

export default function App() {
  const [opened, setOpened] = React.useState(false);

  const title = <Title order={1}>Modal title</Title>
  return (
    <div>
      <Button onClick={() => setOpened(true)}>Open modal</Button>
      <Modal transitionDuration={0} trapFocus={false} opened={opened} closeButtonLabel="Close" title={title} onClose={() => setOpened(false)}>Modal contents</Modal>
    </div>
  );
}
```

**App.test.tsx**

```
import React from 'react';
import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from './App';

test('it opens a modal when the button is clicked', () => {
  render(<App />);

  const button = screen.getByRole('button', { name: 'Open modal' });
  userEvent.click(button);

  const modal = screen.getByRole('dialog');
  const modalTitle = within(modal).getByRole('heading', { name: 'Modal title' });
  const modalContents = within(modal).getByText('Modal contents');
  expect(modal).toBeInTheDocument();
  expect(modalTitle).toBeInTheDocument();
  expect(modalContents).toBeInTheDocument();
});

test('it closes the modal when the close button is clicked', async () => {
  render(<App />);

  const button = screen.getByRole('button', { name: 'Open modal' });
  userEvent.click(button);

  const modal = screen.getByRole('dialog');
  const closeButton = within(modal).getByRole('button', { name: 'Close' });
  userEvent.click(closeButton);

  await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
});
```

### Underlying cause

* `Modal` uses `GroupedTransition`
* `GroupedTransition` uses the `useTransition` hook
* The `useTransition` hook uses `setTimeout` **when the transition duration is not 0**

The problem here is that when the `transitionDuration` prop of a `Modal` is set to 0, that isn't passed on to the `GroupedTransition` (and therefore `useTransition`), causing a `setTimeout` to be used, even when there are no transitions.

### In which browser did the problem occur

JSDOM 16.6.0

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

My suggested fix is to pass the following props to `GroupedTransition` from inside `Modal`:

```
duration={transitionDuration}
exitDuration={transitionDuration}
```

This means that when setting the `transitionDuration` prop of `Modal` to `0` there will be no `setTimeout` used by the `useTransition` hook.

If there's a better solution for this, please let me know.

**Comment by Michael-Xie** [comment]
The warning still exists when using `Modal`. I updated to the latest version 4.2.9. Here is the error I am seeing:
```
    console.error
      Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
          at @mantine/core/GroupedTransition (/home/xiemicha/projects/portal/node_modules/@mantine/core/src/components/Transition/GroupedTransition.tsx:5:3)
          at div
          at @mantine/core/Portal (/home/xiemicha/projects/portal/node_modules/@mantine/core/src/components/Portal/Portal.tsx:10:61)
          at @mantine/core/OptionalPortal (/home/xiemicha/projects/portal/node_modules/@mantine/core/src/components/Portal/OptionalPortal.tsx:32:18)
          at @mantine/core/Modal (/home/xiemicha/projects/portal/node_modules/@mantine/core/src/components/Modal/Modal.tsx:59:14)
          at ReportSetupStepper (/home/xiemicha/projects/portal/src/components/builder/ReportSetupStepper.js:8:2)

      at Object.error (node_modules/@testing-library/react/dist/act-compat.js:55:34)
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnAboutUpdateOnUnmountedFiberInDEV (node_modules/react-dom/cjs/react-dom.development.js:23914:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21840:5)
      at dispatchAction (node_modules/react-dom/cjs/react-dom.development.js:16139:5)
      at node_modules/@mantine/core/src/components/Transition/use-transition.ts:33:9
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:516:19)
```

what are some things that can be done to resolve this?

**Comment by DanielGibbsNZ** [comment]
@Michael-Xie If the issue is related to transitions, I've found that a rather blunt tool to disable them all is to create a file in your repository at `__mocks__/@mantine/hooks` with the following content:

```jsx
export * from '@mantine/hooks'

// This disables transitions for most components, which prevents `setTimeout` calls and the
// resultant, "An update inside a test was not wrapped in act" errors.
export const useReducedMotion = () => {
  return true
}
```

This should disable all transitions across the board.

---

**Update for Mantine v7+:** for this approach to work, you need to make sure that your theme has `respectReducedMotion: true`. If you don't want to set this on the theme in the app, you can do this just for testing, e.g.

```jsx
const mantineThemeTest = { ...mantineTheme, respectReducedMotion: true }
const Wrapper = ({ children }) => (
  <MantineProvider theme={mantineThemeTest}>
    {children}
  </MantineProvider>
)
render(<App />, { wrapper: Wrapper })
```
