### ISSUE TITLE
FileInput breaks if file choosen and new dialog canceled

### ISSUE THREAD

**Issue by D3kion** [mantinedev/mantine#1854]
### Link to the page where something nasty is located

https://mantine.dev/core/file-input/

### Exact quote of what is wrong

I think title is quite informative

Some logs:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at M (FileInput.demo.valueComponent.tsx:78:11)
    at ko (react-dom.production.min.js:166:137)
    at zu (react-dom.production.min.js:215:270)
    at ki (react-dom.production.min.js:291:202)
    at ys (react-dom.production.min.js:279:389)
    at gs (react-dom.production.min.js:279:320)
    at ms (react-dom.production.min.js:279:180)
    at ls (react-dom.production.min.js:270:88)
    at us (react-dom.production.min.js:272:300)
    at jl (react-dom.production.min.js:127:105)
```

P.S.: i didn't try that in my project, sorry if this issue in the lib

**Comment by rtivital** [comment]
Fixed in 5.0.2
