### ISSUE TITLE
error: TypeError: id.replaceAll is not a function

### ISSUE THREAD

**Issue by ArchyInUse** [mantinedev/mantine#1953]
### What package has an issue

@mantine/hooks

### Describe the bug

Hey all, 

I've been developing a next.js app and when I switched to the newest version of mantine, the code breaks (at all pages) stating the following error:
```
error - TypeError: id.replaceAll is not a function
    at getReactId (D:\NewRepos\1d3a\node_modules\@mantine\hooks\cjs\use-id\use-id.js:23:29)
    at Object.useId (D:\NewRepos\1d3a\node_modules\@mantine\hooks\cjs\use-id\use-id.js:26:52)
    at @mantine/core/Modal (D:\NewRepos\1d3a\node_modules\@mantine\core\cjs\Modal\Modal.js:130:24)
    at renderWithHooks (D:\NewRepos\1d3a\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (D:\NewRepos\1d3a\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5731:15)
    at renderElement (D:\NewRepos\1d3a\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (D:\NewRepos\1d3a\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\NewRepos\1d3a\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\NewRepos\1d3a\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (D:\NewRepos\1d3a\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7) {
  page: '/'
```

it worked completely fine before updating and for my friend who is developing with me, it still works.

What I've tried so far:
- updating all packages (failed)
- deleting node_modules and reinstalling

can anyone help?

### What version of @mantine/hooks page do you have in package.json?

^5.0.0

### Do you know how to fix the issue

No

**Comment by rtivital** [comment]
Update Node.js to version 16+
