### ISSUE TITLE
error - TypeError: core.useComponentDefaultProps is not a function

### ISSUE THREAD

**Issue by kandragu** [mantinedev/mantine#1963]
### What package has an issue

@mantine/carousel

### Describe the bug

jsx 
`
 <Carousel mx="auto" withIndicators height={200}>

      <Carousel.Slide>1</Carousel.Slide>

      <Carousel.Slide>2</Carousel.Slide>

      <Carousel.Slide>3</Carousel.Slide>

    </Carousel>
`

package.json
` "@mantine/carousel": "^5.0.0",

  "@mantine/core": "4.2.2",`

it is throwing an error
`TypeError: core.useComponentDefaultProps is not a function
    at @mantine/carousel/Carousel (/Users/.../node_modules/@mantine/carousel/cjs/Carousel.js:65:19)
    at renderWithHooks (/Users/.../node_modules/react-dom/cjs/react-dom-server.browser.development.js:5471:16)
    at renderForwardRef (/Users/.../node_modules/react-dom/cjs/react-dom-server.browser.development.js:5655:18)`

### What version of @mantine/hooks page do you have in package.json?

"@mantine/carousel": "^5.0.0",

**Comment by rtivital** [comment]
All `@mantine/` packages must have the same version, update `@mantine/core` to `5.0.0`
