### ISSUE TITLE
The TextInput throw error

### ISSUE THREAD

**Issue by kisstamasj** [mantinedev/mantine#2645]
### What package has an issue

@mantine/core

### Describe the bug

In the console, there is a following error:
```
next-dev.js?3515:20 Warning: Prop `htmlFor` did not match. Server: "mantine-Rnl4m" Client: "mantine-Rnlcm"
    at label
    at eval (webpack-internal:///./node_modules/@mantine/core/esm/Box/Box.js:45:18)
    at eval (webpack-internal:///./node_modules/@mantine/core/esm/Input/InputLabel/InputLabel.js:43:5)
    at div
    at eval (webpack-internal:///./node_modules/@mantine/core/esm/Box/Box.js:45:18)
    at eval (webpack-internal:///./node_modules/@mantine/core/esm/Input/InputWrapper/InputWrapper.js:63:87)
    at eval (webpack-internal:///./node_modules/@mantine/core/esm/TextInput/TextInput.js:50:86)
    at form
    at div
    at eval (webpack-internal:///./node_modules/@mantine/core/esm/Box/Box.js:45:18)
    at SignInForm (webpack-internal:///./components/SignInForm.tsx:28:77)
    at div
    at PageCenter (webpack-internal:///./components/PageCenter.tsx:11:25)
    at div
    at AuthNotRequired (webpack-internal:///./components/AuthNotRequired.tsx:15:26)
    at Home
    at NotificationsProvider (webpack-internal:///./node_modules/@mantine/notifications/esm/NotificationsProvider/NotificationsProvider.js:67:5)
    at ThemeProvider (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:96:64)
    at MantineProvider (webpack-internal:///./node_modules/@mantine/styles/esm/theme/MantineProvider.js:75:3)
    at AuthProvider (webpack-internal:///./contexts/AuthContext.tsx:60:26)
    at MyApp (webpack-internal:///./pages/_app.tsx:30:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20742)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23635)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:70:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:216:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:407:27) 

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

My package.json:
```
 "@emotion/react": "^11.10.4",
    "@emotion/server": "^11.10.0",
    "@mantine/carousel": "^5.5.4",
    "@mantine/core": "^5.5.4",
    "@mantine/dates": "^5.5.4",
    "@mantine/dropzone": "^5.5.4",
    "@mantine/form": "^5.5.4",
    "@mantine/hooks": "^5.5.4",
    "@mantine/modals": "^5.5.4",
    "@mantine/next": "^5.5.4",
    "@mantine/notifications": "^5.5.4",
    "@mantine/nprogress": "^5.5.4",
    "@mantine/prism": "^5.5.4",
    "@mantine/rte": "^5.5.4",
    "@mantine/spotlight": "^5.5.4",
    "@next/env": "^12.3.1",
    "axios": "^0.27.2",
    "cookie": "^0.5.0",
    "cookies-next": "^2.1.1",
    "dayjs": "^1.11.5",
    "embla-carousel-react": "^7.0.3",
    "next": "12.3.1",
    "react": "18.2.0",
    "react-dom": "18.2.0"
```

### What version of @mantine/hooks page do you have in package.json?

5.5.4

### Do you know how to fix the issue

Yes

### Possible fix

Possible fix for that, in the label element can't use **for** attribute, only **htmlFor**.

**Comment by rtivital** [comment]
TextInput uses useId react hook to generate random id, if that does not work, set `<TextInput id="your-static-id" />`

**Comment by KurtGokhan** [comment]
This is reproducible in Next.js in strict mode for me. Doesn't seem to happen in non-strict mode.
