### ISSUE TITLE
Mantine Carousel core.rem not working

### ISSUE THREAD

**Issue by myagizmaktav** [mantinedev/mantine#3978]
### What package has an issue

@mantine/carousel@latest

### Describe the bug
I fix with @mantine/carousel@5.10.5
Directly giving err on next.

```
TypeError: core.rem is not a function   
    at D:\githubprojects\projectSeriesFrontend\node_modules\@mantine\carousel\cjs\Carousel.styles.js:61:20
    at Object.useStyles [as default] (D:\githubprojects\projectSeriesFrontend\node_modules\@mantine\styles\cjs\tss\create-styles.js:51:23)
    at D:\githubprojects\projectSeriesFrontend\node_modules\@mantine\carousel\cjs\Carousel.js:144:60
    at renderWithHooks (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderForwardRef (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5842:18)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderForwardRef (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5859:5)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderForwardRef (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5859:5)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
error - TypeError: core.rem is not a function
    at D:\githubprojects\projectSeriesFrontend\node_modules\@mantine\carousel\cjs\Carousel.styles.js:61:20
    at Object.useStyles [as default] (D:\githubprojects\projectSeriesFrontend\node_modules\@mantine\styles\cjs\tss\create-styles.js:51:23)
    at D:\githubprojects\projectSeriesFrontend\node_modules\@mantine\carousel\cjs\Carousel.js:144:60
    at renderWithHooks (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderForwardRef (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5842:18)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderForwardRef (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5859:5)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderForwardRef (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5859:5)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14) {
  page: '/'
}
TypeError: core.rem is not a function
    at D:\githubprojects\projectSeriesFrontend\node_modules\@mantine\carousel\cjs\Carousel.styles.js:61:20
    at Object.useStyles [as default] (D:\githubprojects\projectSeriesFrontend\node_modules\@mantine\styles\cjs\tss\create-styles.js:51:23)
    at D:\githubprojects\projectSeriesFrontend\node_modules\@mantine\carousel\cjs\Carousel.js:144:60
    at renderWithHooks (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderForwardRef (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5842:18)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderForwardRef (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5859:5)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderForwardRef (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5859:5)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
error - TypeError: core.rem is not a function
    at D:\githubprojects\projectSeriesFrontend\node_modules\@mantine\carousel\cjs\Carousel.styles.js:61:20
    at Object.useStyles [as default] (D:\githubprojects\projectSeriesFrontend\node_modules\@mantine\styles\cjs\tss\create-styles.js:51:23)
    at D:\githubprojects\projectSeriesFrontend\node_modules\@mantine\carousel\cjs\Carousel.js:144:60
    at renderWithHooks (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderForwardRef (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5842:18)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderForwardRef (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5859:5)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderForwardRef (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5859:5)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderElement (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (D:\githubprojects\projectSeriesFrontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14) {
  page: '/'
}```



### What version of @mantine/hooks page do you have in package.json?

"dependencies": {     "@emotion/react": "^11.10.6",     "@emotion/server": "^11.10.0",     "@mantine/carousel": "6.0.0",     "@mantine/core": "^5.10.5",     "@mantine/dates": "^5.10.5",     "@mantine/dropzone": "^5.10.5",     "@mantine/form": "^5.10.5",     "@mantine/hooks": "^5.10.5",     "@mantine/modals": "^5.10.5",     "@mantine/next": "^5.10.5",     "@mantine/notifications": "^5.10.5",     "@mantine/nprogress": "^5.10.5",     "@mantine/prism": "^5.10.5",     "@mantine/spotlight": "^5.10.5",     "@mantine/tiptap": "^5.10.5",     "@next/font": "^13.2.4",     "@svgr/webpack": "^7.0.0",     "@tabler/icons": "1.119.0",     "@tiptap/extension-link": "^2.0.0-beta.220",     "@tiptap/react": "^2.0.0-beta.220",     "@tiptap/starter-kit": "^2.0.0-beta.220",     "dayjs": "^1.11.7",     "embla-carousel-react": "^7.1.0",     "eslint": "8.35.0",     "eslint-config-next": "13.2.1",     "jotai": "^2.0.2",     "next": "13.2.1",     "react": "18.2.0",     "react-dom": "18.2.0",     "typescript": "4.9.5"   },   "devDependencies": {     "@types/node": "18.14.2",     "@types/react": "18.0.28",     "@types/react-dom": "18.0.11",     "autoprefixer": "^10.4.14",     "eslint-config-prettier": "^8.8.0",     "eslint-plugin-prettier": "^4.2.1",     "eslint-plugin-simple-import-sort": "^10.0.0",     "prettier": "^2.8.7"   }

### If possible, please include a link to a codesandbox with the reproduced problem

_No response_

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

Possible fix = @rtivital

**Comment by cyantree** [comment]
Please provide a sandbox project demonstrating your issue.

Otherwise here's a guess:
Are you maybe mixing v5 and v6 packages? I think `rem()` was introduced in v6 so it might be possible that you're using a v6 carousel package with a v5 core package.

**Comment by myagizmaktav** [comment]
> Please provide a sandbox project demonstrating your issue.
> 
> Otherwise here's a guess: Are you maybe mixing v5 and v6 packages? I think `rem()` was introduced in v6 so it might be possible that you're using a v6 carousel package with a v5 core package.

I delete V6 then I download V5.10.5 then I fix.

**Comment by rtivital** [comment]
All `@mantine/` packages must have the same version in order to work correctly. If you use `@mantine/core@5.x` then you need to install `@mantine/carousel@5.x`
