### ISSUE TITLE
Warning: Prop `data-mantine-script` did not match. Server: "null" Client: "true" with Remix

### ISSUE THREAD

**Issue by alvaro-cuesta** [mantinedev/mantine#5249]
### What package has an issue?

@mantine/core

### Describe the bug

Following the [Remix guide](https://mantine.dev/guides/remix/) I get this warning in the console on initial page render. Using the [Remix template](https://github.com/mantinedev/remix-template) exhibits the same behavior.

```
Warning: Prop `data-mantine-script` did not match. Server: "null" Client: "true"
    at script
    at ColorSchemeScript (http://localhost/build/_shared/chunk-OUBHSCJV.js:1400:5)
    at head
    at html
    at App (http://localhost/build/root-IL7SKKPN.js:225:7)
    at SentryRoot
    at RenderedRoute (http://localhost/build/_shared/chunk-TLAX72HA.js:3817:5)
    at RenderErrorBoundary (http://localhost/build/_shared/chunk-TLAX72HA.js:4393:9)
    at DataRoutes2 (http://localhost/build/_shared/chunk-TLAX72HA.js:4986:5)
    at Router (http://localhost/build/_shared/chunk-TLAX72HA.js:4186:15)
    at RouterProvider2 (http://localhost/build/_shared/chunk-TLAX72HA.js:4849:5)
    at RemixErrorBoundary (http://localhost/build/_shared/chunk-TLAX72HA.js:6923:5)
    at RemixBrowser (http://localhost/build/_shared/chunk-TLAX72HA.js:7534:48)
    at I18nextProvider (http://localhost/build/_shared/chunk-EOCMZ6P7.js:122:5)
console.error @ suppress-nextjs-warning.ts:6
```

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

^7.2.2

### If possible, please include a link to a codesandbox with a minimal reproduction

Cannot include CodeSandbox since this requires Remix. You can use the template here https://github.com/mantinedev/remix-template (you can use "Open in a codespace") since it happens out-of-the-box.

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No (I'd be willing if I knew how to fix this)

**Comment by bricesuazo** [comment]
Having the same issue with Next.js.

 "next": "^14.0.4",
 "@mantine/*": "^7.3.2",

**Comment by rtivital** [comment]
I cannot reproduce the issue with updated remix template with ite bundler – https://github.com/mantinedev/remix-template
