### ISSUE TITLE
List.Item does not work with Next app router

### ISSUE THREAD

**Issue by tahmid-23** [mantinedev/mantine#5346]
### What package has an issue?

@mantine/core

### Describe the bug

When using components such as `List.Item` or `Card.Section` in a Next component without `"use client"` while using the app router, you get the following error:

```
⨯ Internal error: Error: Could not find the module "/workspaces/next-app-min-template/node_modules/@mantine/core/esm/components/List/List.mjs#List#Item" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at /workspaces/next-app-min-template/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:260179
    at eM (/workspaces/next-app-min-template/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:260374)
    at /workspaces/next-app-min-template/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:274925
    at Array.toJSON (/workspaces/next-app-min-template/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:276115)
    at stringify (<anonymous>)
    at /workspaces/next-app-min-template/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:262475
    at ez (/workspaces/next-app-min-template/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:262554)
    at eB (/workspaces/next-app-min-template/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:262955)
    at Timeout._onTimeout (/workspaces/next-app-min-template/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:259453)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

Directly importing and using `ListItem` or `CardSection` does not raise any error.

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.2.2

### Do you know how to fix the issue

No

### Do you want to send a pull request with a fix?

No

**Comment by rtivital** [comment]
https://mantine.dev/guides/next/#compound-components-in-server-components
