### ISSUE TITLE
Cannot read properties of undefined (reading 'extend')

### ISSUE THREAD

**Issue by jamalsoueidan** [mantinedev/mantine#6068]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/dates

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

It's only related to MonthPickerInput component.

The rest of mantine works.

TypeError: Cannot read properties of undefined (reading 'extend')
    at /Users/jamalsoueidan/Development/latest-hydrogen/node_modules/@mantine/dates/esm/utils/get-timezone-offset.mjs:5:7
    at Object.runViteModule (Users/jamalsoueidan/Development/latest-hydrogen/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1171:11)
    at ViteRuntime.directRequest (Users/jamalsoueidan/Development/latest-hydrogen/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1026:60)
    at ViteRuntime.cachedRequest (Users/jamalsoueidan/Development/latest-hydrogen/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:950:79)
    at /node_modules/@mantine/dates/esm/utils/shift-timezone.mjs?v=e8190170:2:31
    at Object.runViteModule (Users/jamalsoueidan/Development/latest-hydrogen/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1171:11)
    at ViteRuntime.directRequest (Users/jamalsoueidan/Development/latest-hydrogen/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1026:60)
    at ViteRuntime.cachedRequest (Users/jamalsoueidan/Development/latest-hydrogen/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:950:79)
    at /node_modules/@mantine/dates/esm/utils/get-default-clamped-date.mjs?v=e8190170:2:31
    at Object.runViteModule (Users/jamalsoueidan/Development/latest-hydrogen/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1171:11)

tsconfig file:

{
  "include": ["./**/*.d.ts", "./**/*.ts", "./**/*.tsx"],
  "compilerOptions": {
    "lib": ["DOM", "DOM.Iterable", "ES2022"],
    "isolatedModules": true,
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "module": "ES2022",
    "target": "ES2022",
    "strict": true,
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
    "allowSyntheticDefaultImports": true,
    "skipLibCheck": true,
    "baseUrl": ".",
    "types": ["@shopify/oxygen-workers-types"],
    "paths": {
      "~/*": ["app/*"]
    },
    "noEmit": true
  }
}

package.json
"type": "module"

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by jamalsoueidan** [comment]
This is maybe related to this:

https://github.com/iamkun/dayjs/issues/1765

**Comment by rtivital** [comment]
I cannot reproduce the issue in any of the official templates, listed on the getting started page.

**Comment by jamalsoueidan** [comment]
No problem @rtivital 

I moved forward to use another lib for dropdown calendar  😄

**Comment by camikura** [comment]
This might be a resolved issue already, but I encountered a similar problem when I specified 
```ts
  build: {
    commonjsOptions: {
      defaultIsModuleExports: false,
    },
  },
```
in the Vite configuration.
