### ISSUE TITLE
Notifications: require is not defined 

### ISSUE THREAD

**Issue by jamalsoueidan** [mantinedev/mantine#6087]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.0

### What package has an issue?

@mantine/notifications

### What framework do you use?

Remix

### In which browsers you can reproduce the issue?

All

### Describe the bug

Getting this error when using notifications and setup

tsconfig file:

{
"include": [".//*.d.ts", ".//.ts", "./**/.tsx"],
"compilerOptions": {
"lib": ["DOM", "DOM.Iterable", "ES2022"],
"isolatedModules": true,
"esModuleInterop": true,
"jsx": "react-jsx",
"moduleResolution": "Bundler",
"resolveJsonModule": true,
"module": "ES2022",
"target": "ES2022",
"strict": true,
"allowJs": true,
"forceConsistentCasingInFileNames": true,
"allowSyntheticDefaultImports": true,
"skipLibCheck": true,
"baseUrl": ".",
"types": ["@shopify/oxygen-workers-types"],
"paths": {
"~/": ["app/"]
},
"noEmit": true
}
}

package.json
"type": "module"

ReferenceError: require is not defined
    at /Users/jamalsoueidan/Development/booking-store/node_modules/prop-types/index.js:9:17
    at Object.runViteModule (Users/jamalsoueidan/Development/booking-store/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1171:17)
    at ViteRuntime.directRequest (Users/jamalsoueidan/Development/booking-store/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1026:78)
    at ViteRuntime.cachedRequest (Users/jamalsoueidan/Development/booking-store/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:949:28)
    at request (Users/jamalsoueidan/Development/booking-store/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:976:128)
    at /node_modules/react-transition-group/esm/CSSTransition.js?v=07d7c5be:4:31
    at Object.runViteModule (Users/jamalsoueidan/Development/booking-store/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1171:11)
    at ViteRuntime.directRequest (Users/jamalsoueidan/Development/booking-store/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1026:60)
    at ViteRuntime.cachedRequest (Users/jamalsoueidan/Development/booking-store/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:950:79)
    at /node_modules/react-transition-group/esm/index.js?v=07d7c5be:1:110

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Please provide a repository based on one of the official templates with a reproduction.
