### ISSUE TITLE
Select Popover triggering act() warnings in tests

### ISSUE THREAD

**Issue by BenWard** [mantinedev/mantine#6121]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.1

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Other, I will specify in the bug description

### Describe the bug

Hi! I'm in the midst of upgrading a project from Mantine 6 to v7, which has actually gone pretty smoothly given the big changes to styling, but I'm hitting some issues right at the end in our tests, and seeing some new state update errors when rendering Select components.

I've been able to distill this down to a raw test case:

```
it('acts out', () => {
    render(
      <MantineProvider>
        <Select data={['One', 'Two', 'Three']} />
      </MantineProvider>
    )

     expect(true).toBe(true);
  });
```

The test passes, but the following warning is generated:

```
console.error
    Warning: An update to @mantine/core/Popover inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at Popover (/Users/benward/.../node_modules/@mantine/core/src/components/Popover/Popover.tsx:49:25)
        at Provider (/Users/benward/.../node_modules/@mantine/core/src/core/utils/create-safe-context/create-safe-context.tsx:12:23)
        at Combobox (/Users/benward/.../node_modules/@mantine/core/src/components/Combobox/Combobox.tsx:48:25)
        at /Users/benward/.../node_modules/@mantine/core/src/components/Select/Select.tsx:24:25
        at MantineThemeProvider (/Users/benward/.../node_modules/@mantine/core/src/core/MantineProvider/MantineThemeProvider/MantineThemeProvider.tsx:17:3)
        at MantineProvider (/Users/benward/.../node_modules/@mantine/core/src/core/MantineProvider/MantineProvider.tsx:14:3)
```

If I wrap `render` in `await act(() => render(…))`, I can swallow the error, but as I understand it that's not a good pattern for render, and shouldn't be necessary as `render` usually handles `act` under the hood — I assume something unexpectedly async is happening in Popover, or Combobox maybe?

This is running with Mantine 7.8.1, jest/jsdom 29.7.0, React 18.2 (nextjs)

Thanks!

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I do not see any issues with `await act(() => render(…))`, this logic is used in Mantine tests. The logic of components is not planned to be changed to satisfy the testing environment limitations, it works as intended in browsers.
