### ISSUE TITLE
FocusTrap relies on a deprecated feature in React 19

### ISSUE THREAD

**Issue by paulzakin** [mantinedev/mantine#6492]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.1

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Hello! 

I'm getting a warning when using Mantine and React 19. I posted the message and stack trace below. It seems spiritually similar to https://github.com/mantinedev/mantine/pull/6446. Just thought I would give you a heads up - apologize if this warning is not helpful. It still works, as far as I can tell, so it is not urgent, at least for me. Thanks!

```
Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.

    at FocusTrap (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:5475:3)
    at Transition (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:5786:3)
    at @mantine/core/Portal (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:5509:43)
    at OptionalPortal (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:5534:33)
    at @mantine/core/PopoverDropdown (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:5833:17)
    at @mantine/core/ComboboxDropdown (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:11684:80)
    at OptionsDropdown (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:12502:3)
    at Provider (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:5372:23)
    at Popover (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:6089:17)
    at Provider (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:5372:23)
    at Combobox (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:12287:17)
    at @mantine/core/Select (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:14964:17)
    at div
    at @mantine/core/Box (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:2661:3)
    at Widget (https://127.0.0.1/build/chunk-5b3443c25c7fa3be.js:10013:11)
    at SelectWidget (https://127.0.0.1/build/chunk-5b3443c25c7fa3be.js:13279:21)
    at div
    at @mantine/core/Box (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:2661:3)
    at @mantine/core/Stack (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:9612:17)
    at div
    at @mantine/core/Box (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:2661:3)
    at @mantine/core/Stack (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:9612:17)
    at WidgetRenderer (https://127.0.0.1/build/chunk-5b3443c25c7fa3be.js:13486:11)
    at WidgetAssembler (https://127.0.0.1/build/chunk-5b3443c25c7fa3be.js:13652:11)
    at div
    at @mantine/core/Box (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:2661:3)
    at @mantine/core/Stack (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:9612:17)
    at Section
    at form
    at div
    at @mantine/core/Box (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:2661:3)
    at JsonForm (https://127.0.0.1/build/chunk-5b3443c25c7fa3be.js:13757:29)
    at div
    at @mantine/core/Box (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:2661:3)
    at @mantine/core/Stack (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:9612:17)
    at div
    at @mantine/core/Box (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:2661:3)
    at @mantine/core/Stack (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:9612:17)
    at Table2 (https://127.0.0.1/build/chunk-84dfbb7a8b45d5fd.js:60:3)
    at div
    at @mantine/core/Box (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:2661:3)
    at @mantine/core/Stack (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:9612:17)
    at QueryClientProvider (https://127.0.0.1/build/chunk-b5fea44eeb1891b0.js:2061:3)
    at PageDataProvider (https://127.0.0.1/build/chunk-6c0261ee02025288.js:894:3)
    at MantineThemeProvider (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:1624:3)
    at MantineProvider (https://127.0.0.1/build/chunk-11d2a476aae9fa5a.js:2057:3)
    at ErrorBoundary (https://127.0.0.1/build/chunk-6c0261ee02025288.js:61:5)
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by paulzakin** [comment]
Awesome, thank you!
